# Generated by Django 5.0.7 on 2024-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
