# Generated by Django 5.1.6 on 2025-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='Без титула', max_length=100),
        ),
    ]
