# Generated by Django 5.0.7 on 2024-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0004_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
