# Generated by Django 5.0.7 on 2024-10-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0009_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udemy.course'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udemy.student'),
        ),
    ]
